# Build settings
markdown: redcarpet
highlighter: pygments

# Site settings
title: "Kreate."
description: "Who we are, and what we stand for."

email: "tom@kreate.ca"
#blog logo
logo: "/assets/images/kreate-logo.png"
k: "/assets/images/just-the-k.png"
# blog cover
cover: "/assets/images/miklos-working.jpg"

name: 'Kreate Solutions'
author: 'Kreate Solutions'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://blogs.kreate.ca" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/kreatenow
    desc: Follow us on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	facebook
    url:	https://facebook.com/kreatesolutions
    desc: Connect with us on facebook
    share_url: //www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  # - icon:	github
  #   url:	https://github.com/dirkfabisch
  #   desc:	Fork me on github
  #   share_url:
  #   share_title:
  #   share_link:

  # - icon:	google-plus
  #   url:	https://google.com/???
  #   desc:	Add me on google+
  #   share_url:
  #   share_title:
  #   share_link:
